# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19110ae25b163c9da641f75d3e6a6b745f3de71fc1332e7e548a2b867302a372fd9daa162c34c5f8c0a02c6af88fd8ca0864548e740fd95d2e7bbc61f18099b

test:
  secret_key_base: e53042e3e8d7f55651bfdb7318d5af46d1c2d4f2346612589ba0df6f2eed5676d8d38e3b48f00e9a8bd9f7f18e316ffb937d8f0c9181e2b8aa1e10da61ea5aa9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
